### ISSUE TITLE
Mismatched dependencies in text package

### ISSUE THREAD

**Issue by darmie** [servo/pathfinder#531]
![Screenshot 2022-12-29 at 04 33 02](https://user-images.githubusercontent.com/848002/209903890-978b0ef0-31b3-484a-8a3f-92520884a8ba.png)

**Comment by TakingFire** [comment]
From #445, adding the following to your `Cargo.toml` file should resolve the issue.
```toml
[patch.crates-io]
pathfinder_geometry = {git = "https://github.com/servo/pathfinder/"}
pathfinder_simd = {git = "https://github.com/servo/pathfinder/"}
```
